# Generated by Django 3.2.25 on 2025-02-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250217_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='default_homepage',
        ),
    ]
