# Generated by Django 3.2.25 on 2025-03-19 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=100)),
                ('pos_x', models.IntegerField(blank=True, null=True)),
                ('pos_y', models.IntegerField(blank=True, null=True)),
                ('area_w', models.IntegerField(blank=True, null=True)),
                ('area_l', models.IntegerField(blank=True, null=True)),
                ('layer', models.CharField(blank=True, max_length=10, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('bin_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_area', to='warehouse.area')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bin_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bin_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('type_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
                ('type_vn_name', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemtype_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('series', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('wh_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('wh_name', models.CharField(max_length=100)),
                ('wh_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('wh_plant', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_bg', models.ImageField(blank=True, null=True, upload_to='warehouse_images/')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('unit_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unittype_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockOutFormDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(max_length=20)),
                ('product_order', models.CharField(blank=True, max_length=20, null=True)),
                ('version_no', models.CharField(blank=True, max_length=20, null=True)),
                ('version_seq', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_no', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_unit', models.CharField(max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockout_form_create_by', to=settings.AUTH_USER_MODEL)),
                ('order_bin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockout_order_bin', to='warehouse.bin')),
            ],
        ),
        migrations.CreateModel(
            name='StockInForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(max_length=20)),
                ('product_order', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_no', models.CharField(blank=True, max_length=20, null=True)),
                ('version_no', models.CharField(blank=True, max_length=20, null=True)),
                ('version_seq', models.CharField(blank=True, max_length=20, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_no', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('post_date', models.CharField(blank=True, max_length=20, null=True)),
                ('order_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('supplier', models.CharField(blank=True, max_length=20, null=True)),
                ('sap_mtr_no', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockin_form_create_by', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockin_itemtype', to='warehouse.itemtype')),
                ('order_bin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockin_order_bin', to='warehouse.bin')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_plant_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_plant_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('mvt_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mvt_name', models.CharField(max_length=20)),
                ('mvt_vn_name', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mvt_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bin_Value_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('product_order', models.CharField(max_length=50)),
                ('purchase_no', models.CharField(blank=True, max_length=50, null=True)),
                ('version_no', models.CharField(blank=True, max_length=50, null=True)),
                ('version_seq', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(max_length=5)),
                ('plus_qty', models.IntegerField()),
                ('minus_qty', models.IntegerField()),
                ('remain_qty', models.IntegerField()),
                ('purchase_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_hist_bin', to='warehouse.bin')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bin_value_hist_create_by', to=settings.AUTH_USER_MODEL)),
                ('mvt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockin_hist_mvt', to='warehouse.movementtype')),
            ],
        ),
        migrations.CreateModel(
            name='Bin_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_order', models.CharField(max_length=50)),
                ('purchase_no', models.CharField(blank=True, max_length=50, null=True)),
                ('version_no', models.CharField(blank=True, max_length=50, null=True)),
                ('version_seq', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(max_length=5)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('purchase_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=5)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_bin', to='warehouse.bin')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bin_value_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attr_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('attr_name', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attr_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_warehouse', to='warehouse.warehouse'),
        ),
    ]
