# Generated by Django 3.2.25 on 2025-02-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_l',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='area_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='pos_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='pos_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
