# Generated by Django 3.2.25 on 2025-03-19 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockOutFormDetail',
            new_name='StockOutForm',
        ),
    ]
