# Generated by Django 3.2.25 on 2025-03-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_stockoutformdetail_stockoutform'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin_value',
            name='stockin_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='value_stockin_form', to='warehouse.stockinform'),
        ),
        migrations.AddField(
            model_name='bin_value',
            name='stockout_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='value_stockout_form', to='warehouse.stockoutform'),
        ),
    ]
