# Generated by Django 3.2.25 on 2025-02-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20250218_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='bin_l',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='bin_w',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='pos_y',
        ),
    ]
