# Generated by Django 3.2.25 on 2025-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20250319_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin_value',
            name='stockin_form',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bin_value',
            name='stockout_form',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
