# Generated by Django 3.2.25 on 2025-02-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20250221_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinformdetail',
            name='packing_type',
        ),
        migrations.AddField(
            model_name='area',
            name='layer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
