# Generated by Django 3.2.25 on 2025-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20250227_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='layer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
