# Generated by Django 3.2.25 on 2025-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20250319_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinform',
            name='lot_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
