# Generated by Django 3.2.25 on 2025-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_stockinform_lot_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutform',
            name='item_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
