# Generated by Django 3.2.25 on 2025-03-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_stockoutform_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin_value',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
