# Generated by Django 3.2.25 on 2025-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_stockinformdetail_packing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='type_vn_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movementtype',
            name='mvt_vn_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
