# Generated by Django 3.2.25 on 2025-03-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20250311_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinformdetail',
            name='packing_type',
        ),
    ]
