# Generated by Django 3.2.25 on 2025-04-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20250331_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='bin_value',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='bin_value',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='bin_value',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='bin_value_history',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='bin_value_history',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='bin_value_history',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='bin_value_history',
            name='mvt',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.RemoveField(
            model_name='stockinform',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='stockinform',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='stockinform',
            name='order_bin',
        ),
        migrations.RemoveField(
            model_name='stockoutform',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='stockoutform',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='stockoutform',
            name='order_bin',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Bin_Value',
        ),
        migrations.DeleteModel(
            name='Bin_Value_History',
        ),
        migrations.DeleteModel(
            name='StockInForm',
        ),
        migrations.DeleteModel(
            name='StockOutForm',
        ),
    ]
