# Generated by Django 3.2.25 on 2025-03-13 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0008_remove_stockinformdetail_packing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('size_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sizetype_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
