# Generated by Django 3.2.25 on 2025-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20250401_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='wh_former_func',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wh_packing_func',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wh_product_func',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wh_wip_func',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
