# Generated by Django 3.2.25 on 2025-03-13 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0009_sizetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeType',
            new_name='Size',
        ),
    ]
