# Generated by Django 3.2.25 on 2025-03-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_rename_sizetype_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
