# Generated by Django 3.2.25 on 2025-04-01 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0009_auto_20250401_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('series', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockOutForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(max_length=20)),
                ('product_order', models.CharField(blank=True, max_length=20, null=True)),
                ('version_no', models.CharField(blank=True, max_length=20, null=True)),
                ('version_seq', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_no', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_unit', models.CharField(max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_stockout_form_create_by', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_stockout_itemtype', to='warehouse.itemtype')),
                ('order_bin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_stockout_order_bin', to='warehouse.bin')),
            ],
        ),
        migrations.CreateModel(
            name='StockInForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(max_length=20)),
                ('product_order', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_no', models.CharField(blank=True, max_length=20, null=True)),
                ('version_no', models.CharField(blank=True, max_length=20, null=True)),
                ('version_seq', models.CharField(blank=True, max_length=20, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_no', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('post_date', models.CharField(blank=True, max_length=20, null=True)),
                ('order_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('supplier', models.CharField(blank=True, max_length=20, null=True)),
                ('sap_mtr_no', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_stockin_form_create_by', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_stockin_itemtype', to='warehouse.itemtype')),
                ('order_bin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_stockin_order_bin', to='warehouse.bin')),
            ],
        ),
        migrations.CreateModel(
            name='Bin_Value_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('product_order', models.CharField(max_length=50)),
                ('purchase_no', models.CharField(blank=True, max_length=50, null=True)),
                ('version_no', models.CharField(blank=True, max_length=50, null=True)),
                ('version_seq', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(max_length=5)),
                ('plus_qty', models.IntegerField()),
                ('minus_qty', models.IntegerField()),
                ('remain_qty', models.IntegerField()),
                ('purchase_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_bin_value_hist_bin', to='warehouse.bin')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_bin_value_hist_create_by', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_bin_value_hist_itemtype', to='warehouse.itemtype')),
                ('mvt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_bin_value_hist_mvt', to='warehouse.movementtype')),
            ],
        ),
        migrations.CreateModel(
            name='Bin_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_order', models.CharField(max_length=50)),
                ('purchase_no', models.CharField(blank=True, max_length=50, null=True)),
                ('version_no', models.CharField(blank=True, max_length=50, null=True)),
                ('version_seq', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(max_length=5)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('purchase_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=5)),
                ('stockin_form', models.CharField(blank=True, max_length=20, null=True)),
                ('stockout_form', models.CharField(blank=True, max_length=20, null=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_bin_value_bin', to='warehouse.bin')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_bin_value_itemtype', to='warehouse.itemtype')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packing_bin_value_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
